import type { Topic, AppState } from './types'

// Radial layout: center (350,265), ring1 r=115, ring2 r=210
export const TOPICS: Topic[] = [
  {
    id: 'number-sense',
    name: 'Number Sense',
    icon: '∞',
    mastery: 81,
    xp: 1340,
    color: '#00d4ff',
    x: 350, y: 265,
    dependencies: [],
    weakPatterns: [
      { id: 'ns1', name: 'Place value confusion', description: 'Mixing up hundreds and thousands positions', frequency: 24 },
      { id: 'ns2', name: 'Rounding errors', description: 'Incorrect rounding when crossing 5 boundary', frequency: 18 },
    ],
    history: [
      { date: 'May 15', mastery: 62, sessions: 3 },
      { date: 'May 16', mastery: 66, sessions: 4 },
      { date: 'May 17', mastery: 70, sessions: 2 },
      { date: 'May 18', mastery: 73, sessions: 5 },
      { date: 'May 19', mastery: 75, sessions: 3 },
      { date: 'May 20', mastery: 79, sessions: 4 },
      { date: 'May 21', mastery: 81, sessions: 3 },
    ],
  },
  {
    id: 'addition',
    name: 'Addition',
    icon: '+',
    mastery: 74,
    xp: 980,
    color: '#06d6a0',
    x: 350, y: 150,
    dependencies: ['number-sense'],
    weakPatterns: [
      { id: 'ad1', name: 'Carrying in multi-digit', description: 'Forgetting to carry over to next column', frequency: 61 },
      { id: 'ad2', name: '3-number chains', description: 'Accuracy drops with 3+ numbers added', frequency: 38 },
    ],
    history: [
      { date: 'May 15', mastery: 50, sessions: 2 },
      { date: 'May 16', mastery: 55, sessions: 3 },
      { date: 'May 17', mastery: 60, sessions: 4 },
      { date: 'May 18', mastery: 64, sessions: 3 },
      { date: 'May 19', mastery: 68, sessions: 5 },
      { date: 'May 20', mastery: 71, sessions: 2 },
      { date: 'May 21', mastery: 74, sessions: 4 },
    ],
  },
  {
    id: 'subtraction',
    name: 'Subtraction',
    icon: '−',
    mastery: 58,
    xp: 720,
    color: '#f59e0b',
    x: 235, y: 265,
    dependencies: ['number-sense'],
    weakPatterns: [
      { id: 'sb1', name: 'Borrowing across zeros', description: 'Errors when borrowing through a zero column', frequency: 77 },
      { id: 'sb2', name: 'Negative mental jumps', description: 'Switching direction mid-calculation', frequency: 44 },
    ],
    history: [
      { date: 'May 15', mastery: 38, sessions: 1 },
      { date: 'May 16', mastery: 42, sessions: 2 },
      { date: 'May 17', mastery: 45, sessions: 3 },
      { date: 'May 18', mastery: 49, sessions: 4 },
      { date: 'May 19', mastery: 52, sessions: 3 },
      { date: 'May 20', mastery: 55, sessions: 5 },
      { date: 'May 21', mastery: 58, sessions: 2 },
    ],
  },
  {
    id: 'multiplication',
    name: 'Multiplication',
    icon: '×',
    mastery: 68,
    xp: 860,
    color: '#a78bfa',
    x: 465, y: 265,
    dependencies: ['number-sense'],
    weakPatterns: [
      { id: 'ml1', name: '2-digit × 2-digit', description: 'Partial product placement errors', frequency: 72 },
      { id: 'ml2', name: 'Times table gaps', description: '7s and 8s tables have lower accuracy', frequency: 53 },
      { id: 'ml3', name: 'Zero handling', description: 'Multiplying numbers ending in 0', frequency: 31 },
    ],
    history: [
      { date: 'May 15', mastery: 44, sessions: 3 },
      { date: 'May 16', mastery: 49, sessions: 4 },
      { date: 'May 17', mastery: 54, sessions: 3 },
      { date: 'May 18', mastery: 58, sessions: 5 },
      { date: 'May 19', mastery: 62, sessions: 4 },
      { date: 'May 20', mastery: 65, sessions: 3 },
      { date: 'May 21', mastery: 68, sessions: 4 },
    ],
  },
  {
    id: 'division',
    name: 'Division',
    icon: '÷',
    mastery: 44,
    xp: 520,
    color: '#ff3d6b',
    x: 350, y: 380,
    dependencies: ['number-sense', 'multiplication'],
    weakPatterns: [
      { id: 'dv1', name: 'Long division steps', description: 'Losing track of intermediate steps', frequency: 85 },
      { id: 'dv2', name: 'Remainder handling', description: 'Errors when dealing with remainders', frequency: 68 },
    ],
    history: [
      { date: 'May 15', mastery: 25, sessions: 1 },
      { date: 'May 16', mastery: 28, sessions: 2 },
      { date: 'May 17', mastery: 32, sessions: 3 },
      { date: 'May 18', mastery: 36, sessions: 2 },
      { date: 'May 19', mastery: 39, sessions: 4 },
      { date: 'May 20', mastery: 42, sessions: 3 },
      { date: 'May 21', mastery: 44, sessions: 2 },
    ],
  },
  {
    id: 'fractions',
    name: 'Fractions',
    icon: '½',
    mastery: 52,
    xp: 630,
    color: '#fb923c',
    x: 498, y: 110,
    dependencies: ['addition', 'multiplication'],
    weakPatterns: [
      { id: 'fr1', name: 'Unlike denominators', description: 'Finding LCM for addition/subtraction', frequency: 80 },
      { id: 'fr2', name: 'Mixed number ops', description: 'Improper fraction conversion errors', frequency: 55 },
    ],
    history: [
      { date: 'May 15', mastery: 30, sessions: 1 },
      { date: 'May 16', mastery: 35, sessions: 2 },
      { date: 'May 17', mastery: 39, sessions: 3 },
      { date: 'May 18', mastery: 43, sessions: 2 },
      { date: 'May 19', mastery: 46, sessions: 3 },
      { date: 'May 20', mastery: 49, sessions: 4 },
      { date: 'May 21', mastery: 52, sessions: 2 },
    ],
  },
  {
    id: 'decimals',
    name: 'Decimals',
    icon: '.',
    mastery: 63,
    xp: 740,
    color: '#34d399',
    x: 202, y: 110,
    dependencies: ['addition', 'subtraction'],
    weakPatterns: [
      { id: 'dc1', name: 'Decimal alignment', description: 'Misaligning decimal points in addition', frequency: 48 },
      { id: 'dc2', name: 'Decimal × decimal', description: 'Counting decimal places after multiplication', frequency: 62 },
    ],
    history: [
      { date: 'May 15', mastery: 42, sessions: 2 },
      { date: 'May 16', mastery: 47, sessions: 3 },
      { date: 'May 17', mastery: 51, sessions: 2 },
      { date: 'May 18', mastery: 55, sessions: 4 },
      { date: 'May 19', mastery: 58, sessions: 3 },
      { date: 'May 20', mastery: 61, sessions: 2 },
      { date: 'May 21', mastery: 63, sessions: 3 },
    ],
  },
  {
    id: 'percentages',
    name: 'Percentages',
    icon: '%',
    mastery: 39,
    xp: 410,
    color: '#e879f9',
    x: 202, y: 420,
    dependencies: ['division', 'decimals'],
    weakPatterns: [
      { id: 'pc1', name: 'Percent of a number', description: 'Converting % to decimal before multiplying', frequency: 70 },
      { id: 'pc2', name: 'Reverse percentage', description: 'Finding the original value from a percentage', frequency: 82 },
    ],
    history: [
      { date: 'May 15', mastery: 20, sessions: 1 },
      { date: 'May 16', mastery: 24, sessions: 1 },
      { date: 'May 17', mastery: 27, sessions: 2 },
      { date: 'May 18', mastery: 30, sessions: 2 },
      { date: 'May 19', mastery: 33, sessions: 3 },
      { date: 'May 20', mastery: 36, sessions: 2 },
      { date: 'May 21', mastery: 39, sessions: 2 },
    ],
  },
  {
    id: 'speed-math',
    name: 'Speed Math',
    icon: '⚡',
    mastery: 55,
    xp: 670,
    color: '#fbbf24',
    x: 498, y: 420,
    dependencies: ['multiplication', 'division'],
    weakPatterns: [
      { id: 'sm1', name: 'Under time pressure', description: 'Accuracy drops by 20%+ when timed', frequency: 65 },
      { id: 'sm2', name: 'Vedic shortcuts', description: 'Inconsistent use of fast calculation tricks', frequency: 40 },
    ],
    history: [
      { date: 'May 15', mastery: 32, sessions: 2 },
      { date: 'May 16', mastery: 37, sessions: 3 },
      { date: 'May 17', mastery: 41, sessions: 2 },
      { date: 'May 18', mastery: 45, sessions: 3 },
      { date: 'May 19', mastery: 49, sessions: 4 },
      { date: 'May 20', mastery: 52, sessions: 3 },
      { date: 'May 21', mastery: 55, sessions: 2 },
    ],
  },
]

export const INITIAL_STATE: AppState = {
  screen: 'dashboard',
  activeTopicId: null,
  streak: 7,
  totalXp: 6870,
  totalSessions: 48,
  accuracy: 73,
}

export const DAILY_ACTIVITY = [
  { day: 'Mon', sessions: 3, xp: 420 },
  { day: 'Tue', sessions: 5, xp: 680 },
  { day: 'Wed', sessions: 2, xp: 290 },
  { day: 'Thu', sessions: 6, xp: 810 },
  { day: 'Fri', sessions: 4, xp: 550 },
  { day: 'Sat', sessions: 7, xp: 920 },
  { day: 'Sun', sessions: 3, xp: 410 },
]
